# Generated by Django 5.2.8 on 2025-11-14 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(null=True)),
                ('prioridade', models.IntegerField(choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta'), (4, 'Urgente')], default=2)),
                ('setor', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('ATENDIMENTO', 'Em Atendimento'), ('RESOLVIDO', 'Resolvido'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('user_criacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
